import assert from 'node:assert/strict';
import {readFile,access,stat} from 'node:fs/promises';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
const root=resolve(import.meta.dirname,'..');
const read=name=>readFile(resolve(root,'dist',name),'utf8');
const html=await read('index.html');const config=JSON.parse(await readFile(resolve(root,'site.config.json'),'utf8'));
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,'unique IDs');
for(const match of html.matchAll(/href="#([^"]+)"/g))assert(ids.includes(match[1]),`anchor ${match[1]}`);
assert.equal([...html.matchAll(/<h1\b/g)].length,1,'one H1');assert(html.includes('<html lang="ko">'));
for(const tag of ['title','description','canonical','og:title','og:description','og:image','og:url','twitter:card','application/ld+json'])assert(html.includes(tag),tag);
const origin=new URL(config.siteUrl).origin;assert(html.includes(`rel="canonical" href="${origin}/"`));
const robots=await read('robots.txt');const sitemap=await read('sitemap.xml');assert(robots.includes(origin+'/sitemap.xml'));assert(sitemap.includes(`<loc>${origin}/</loc>`));assert(!sitemap.includes('#'),'sitemap contains pages, not scene anchors');
assert(html.includes('tel:+821068566622'));assert(html.includes('mailto:seoah.lab@gmail.com'));
for(const match of html.matchAll(/(?:src|href)="(\/[^"#]*)"/g))await access(resolve(root,'dist',match[1].slice(1)));
for(const panel of ['delivery-panel','delivery-editable','delivery-advanced'])assert(html.includes(`id="${panel}"`),'static no-JS content');
for(const aria of html.matchAll(/aria-(?:controls|labelledby)="([^"]+)"/g))for(const id of aria[1].split(' '))assert(ids.includes(id),'ARIA reference '+id);
const css=await read('style.css');assert(css.includes('prefers-reduced-motion'));assert(css.includes(':focus-visible'));assert(css.includes('.delivery-panel[hidden]'));
const app=await read('app.js');for(const event of ['partnership_cta_click','email_click','phone_click'])assert(html.includes(event));for(const event of ['live_demo_click','project_view'])assert(app.includes(event));
for(const file of ['app.js','content.js','site-settings.js'])execFileSync(process.execPath,['--check',resolve(root,'dist',file)]);
const schema=JSON.parse(html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1]);assert.equal(schema['@graph'][0].name,'이서아');
const og=await stat(resolve(root,'dist',config.ogImage.slice(1)));assert(og.size<300000,'share image under 300 KB');
console.log('PASS: SEO metadata / schema / canonical / robots / sitemap / assets / CTA hrefs / headings / ARIA references / no-JS content / motion and focus CSS / JS syntax / OG payload');
console.log('Browser rendering, runtime console, actual clicks, HTTP 404 and CWV measurement are separate pending checks.');
